import { afterEach, describe, expect, it } from "vitest";
import { loadConfig } from "../../apps/server/src/config";
import { assertSafeSvg, parseLatexDiagnostics, resolveCompileProfile } from "../../apps/server/src/latex/compiler";

const originalEnv = { ...process.env };

describe("compile profile selection", () => {
  it.each(["中文", String.raw`\usepackage{tikz,fontspec}`, String.raw`\documentclass[12pt]{ctexart}`, String.raw`\setmainfont{FandolSong}`])("selects XeLaTeX for %s", (source) => {
    expect(resolveCompileProfile(source)).toBe("xelatex");
  });
  it("preserves an explicit profile and the traditional default", () => {
    expect(resolveCompileProfile("x^2")).toBe("latex");
    expect(resolveCompileProfile("中文", "latex")).toBe("latex");
  });
});

afterEach(() => {
  for (const key of Object.keys(process.env)) {
    if (!(key in originalEnv)) delete process.env[key];
  }
  Object.assign(process.env, originalEnv);
});

describe("LaTeX server configuration", () => {
  it("uses CLI options before environment options", () => {
    process.env.TIKZ_SERVER_PORT = "6000";
    process.env.TIKZ_SERVER_HOST = "0.0.0.0";
    const config = loadConfig(["--port", "7000", "--host=127.0.0.1"]);
    expect(config.port).toBe(7000);
    expect(config.host).toBe("127.0.0.1");
  });

  it("falls back for invalid ports and limits", () => {
    process.env.TIKZ_SERVER_PORT = "99999";
    process.env.TIKZ_LATEX_TIMEOUT_MS = "invalid";
    const config = loadConfig([]);
    expect(config.port).toBe(5173);
    expect(config.timeoutMs).toBe(20_000);
  });
});

describe("server-side SVG safety gate", () => {
  it("accepts ordinary dvisvgm-style SVG", () => {
    expect(() => assertSafeSvg("<?xml version=\"1.0\"?><svg xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M0 0L1 1\"/><use href=\"#glyph0\"/></svg>")).not.toThrow();
  });
  it("accepts the generator comment emitted by real dvisvgm", () => {
    expect(() => assertSafeSvg("<?xml version=\"1.0\"?>\n<!-- This file was generated by dvisvgm 3.6 -->\n<svg xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M0 0\"/></svg>")).not.toThrow();
  });

  it.each([
    "<svg><script>alert(1)</script></svg>",
    "<svg><path onclick=\"alert(1)\"/></svg>",
    "<svg><image href=\"https://example.invalid/tracker.png\"/></svg>",
    "<!DOCTYPE svg [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><svg>&xxe;</svg>",
    "<svg><foreignObject><div>unsafe</div></foreignObject></svg>"
  ])("rejects active or external content", (svg) => {
    expect(() => assertSafeSvg(svg)).toThrow();
  });
});

describe("LaTeX diagnostics", () => {
  it("extracts file-line-error output without exposing paths", () => {
    expect(parseLatexDiagnostics("/tmp/private/input.tex:12: Undefined control sequence.")).toEqual([
      { file: "input.tex", line: 12, message: "Undefined control sequence." }
    ]);
  });
});
